@extends('admin.layouts.app')
@section('title', 'Security Event - LesGo Admin')
@section('header', 'Security Event #'.$securityEvent->id)

@section('content')
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
    <div class="lg:col-span-2 space-y-6">
        <div class="bg-white rounded-xl shadow-sm p-6"><div class="flex items-center gap-3 mb-4"><span class="px-3 py-1 rounded-full text-sm font-medium {{ $securityEvent->severity === 'critical' ? 'bg-red-100 text-red-700' : ($securityEvent->severity === 'high' ? 'bg-orange-100 text-orange-700' : 'bg-yellow-100 text-yellow-700') }}">{{ ucfirst($securityEvent->severity) }}</span><span class="px-3 py-1 rounded-full text-sm {{ $securityEvent->is_resolved ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' }}">{{ $securityEvent->is_resolved ? 'Resolved' : 'Open' }}</span></div><h3 class="text-xl font-bold mb-3">{{ str_replace('_', ' ', $securityEvent->event_type) }}</h3><p class="text-gray-700 whitespace-pre-wrap">{{ $securityEvent->description ?: 'No description was provided.' }}</p></div>
        @if($securityEvent->event_data || $securityEvent->metadata)<div class="bg-white rounded-xl shadow-sm p-6"><h3 class="font-semibold mb-3">Event Data</h3><pre class="bg-gray-900 text-gray-100 rounded-lg p-4 text-xs overflow-auto">{{ json_encode(['event_data'=>$securityEvent->event_data,'metadata'=>$securityEvent->metadata], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre></div>@endif
        <form method="POST" action="{{ route('admin.security-events.update', $securityEvent) }}" class="bg-white rounded-xl shadow-sm p-6">@csrf @method('PATCH')<h3 class="font-semibold mb-4">Resolution</h3><input type="hidden" name="is_resolved" value="{{ $securityEvent->is_resolved ? 0 : 1 }}">@if(!$securityEvent->is_resolved)<label class="block text-sm font-medium mb-1">Resolution notes</label><textarea name="resolution_notes" required rows="5" class="w-full border rounded-lg px-3 py-2 mb-4">{{ old('resolution_notes') }}</textarea><button class="bg-green-600 text-white px-5 py-2 rounded-lg">Resolve Event</button>@else<p class="text-sm text-gray-700 whitespace-pre-wrap mb-4">{{ $securityEvent->resolution_notes }}</p><p class="text-xs text-gray-500 mb-4">Resolved by {{ $securityEvent->resolved_by }} on {{ $securityEvent->resolved_at?->format('M d, Y H:i') }}</p><button class="bg-orange-600 text-white px-5 py-2 rounded-lg">Reopen Event</button>@endif</form>
    </div>
    <div class="bg-white rounded-xl shadow-sm p-6 h-fit text-sm space-y-4"><div><p class="text-xs text-gray-500">User</p><p>{{ $securityEvent->user->name ?? 'Unknown' }}</p><p class="text-gray-500">{{ $securityEvent->user->email ?? '—' }}</p></div><div><p class="text-xs text-gray-500">Source</p><p>{{ $securityEvent->source ?? '—' }}</p></div><div><p class="text-xs text-gray-500">IP address</p><p class="font-mono">{{ $securityEvent->ip_address ?? '—' }}</p></div><div><p class="text-xs text-gray-500">Detected</p><p>{{ $securityEvent->detected_at?->format('M d, Y H:i:s') }}</p></div><div><p class="text-xs text-gray-500">User agent</p><p class="break-words">{{ $securityEvent->user_agent ?? '—' }}</p></div></div>
</div>
@endsection
