@extends('admin.layouts.app')
@section('title', $partner->name.' Menu - LesGo Admin')
@section('header', $partner->name.' Menu')

@section('actions')
<a href="{{ route('admin.partners.staff.index', $partner) }}" class="border px-4 py-2 rounded-lg text-sm">Manage Staff</a>
<a href="{{ route('admin.partners.show', $partner) }}" class="bg-gray-800 text-white px-4 py-2 rounded-lg text-sm">Back to Partner</a>
@endsection

@section('content')
<div class="grid grid-cols-1 xl:grid-cols-3 gap-6 mb-8">
    <form method="POST" action="{{ route('admin.partners.menu.categories.store', $partner) }}" class="bg-white rounded-xl shadow-sm p-6 space-y-4">@csrf<h3 class="font-semibold text-lg">Add Category</h3><div><label class="block text-sm mb-1">Name</label><input name="name" required class="w-full border rounded-lg px-3 py-2"></div><div class="grid grid-cols-3 gap-3"><div><label class="block text-sm mb-1">Emoji</label><input name="icon_emoji" maxlength="10" class="w-full border rounded-lg px-3 py-2"></div><div class="col-span-2"><label class="block text-sm mb-1">Sort order</label><input type="number" name="sort_order" value="0" min="0" class="w-full border rounded-lg px-3 py-2"></div></div><div><label class="block text-sm mb-1">Description</label><textarea name="description" rows="2" class="w-full border rounded-lg px-3 py-2"></textarea></div><div class="flex gap-5"><label><input type="checkbox" name="is_active" value="1" checked> Active</label><label><input type="checkbox" name="is_popular" value="1"> Popular</label></div><button class="bg-blue-600 text-white px-4 py-2 rounded-lg">Add Category</button></form>

    <form method="POST" action="{{ route('admin.partners.menu.items.store', $partner) }}" class="xl:col-span-2 bg-white rounded-xl shadow-sm p-6 space-y-4">@csrf<h3 class="font-semibold text-lg">Add Menu Item</h3>@if($partner->menuCategories->isEmpty())<p class="text-sm text-orange-600">Create a category before adding items.</p>@else<div class="grid grid-cols-1 md:grid-cols-3 gap-3"><div><label class="block text-sm mb-1">Name</label><input name="name" required class="w-full border rounded-lg px-3 py-2"></div><div><label class="block text-sm mb-1">Category</label><select name="menu_category_id" required class="w-full border rounded-lg px-3 py-2">@foreach($partner->menuCategories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div><label class="block text-sm mb-1">Price</label><input type="number" name="price" min="0" step="0.01" required class="w-full border rounded-lg px-3 py-2"></div></div><div class="grid grid-cols-1 md:grid-cols-4 gap-3"><div><label class="block text-sm mb-1">Original price</label><input type="number" name="original_price" min="0" step="0.01" class="w-full border rounded-lg px-3 py-2"></div><div><label class="block text-sm mb-1">Unit</label><input name="unit" class="w-full border rounded-lg px-3 py-2" placeholder="piece, pack, kg"></div><div><label class="block text-sm mb-1">Sort order</label><input type="number" name="sort_order" value="0" min="0" class="w-full border rounded-lg px-3 py-2"></div><div><label class="block text-sm mb-1">Image URL</label><input type="url" name="image_url" class="w-full border rounded-lg px-3 py-2"></div></div><div><label class="block text-sm mb-1">Description</label><textarea name="description" rows="2" class="w-full border rounded-lg px-3 py-2"></textarea></div><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="block text-sm mb-1">Tags (comma-separated)</label><input name="tags" class="w-full border rounded-lg px-3 py-2"></div><div><label class="block text-sm mb-1">Options (JSON)</label><input name="options" class="w-full border rounded-lg px-3 py-2" placeholder='{"sizes":["S","M"]}'></div></div><div class="flex flex-wrap gap-5 text-sm"><label><input type="checkbox" name="is_available" value="1" checked> Available</label><label><input type="checkbox" name="is_popular" value="1"> Popular</label><label><input type="checkbox" name="is_featured" value="1"> Featured</label><label><input type="checkbox" name="is_best_seller" value="1"> Best seller</label><label><input type="checkbox" name="requires_prescription" value="1"> Prescription required</label></div><button class="bg-blue-600 text-white px-4 py-2 rounded-lg">Add Item</button>@endif</form>
</div>

<div class="space-y-6">
@forelse($partner->menuCategories as $category)
    <section class="bg-white rounded-xl shadow-sm overflow-hidden">
        <div class="p-5 border-b flex flex-wrap justify-between items-center gap-3"><div><h3 class="font-semibold text-lg">{{ $category->icon_emoji }} {{ $category->name }}</h3><p class="text-xs text-gray-500">{{ $category->items->count() }} item(s) · Order {{ $category->sort_order }} · {{ $category->is_active ? 'Active' : 'Inactive' }}</p></div><div class="flex gap-3"><details class="relative"><summary class="cursor-pointer text-blue-600 text-sm list-none">Edit category</summary><div class="absolute right-0 z-10 mt-2 w-96 bg-white border shadow-xl rounded-lg p-4"><form method="POST" action="{{ route('admin.partners.menu.categories.update', [$partner, $category]) }}" class="space-y-3">@csrf @method('PUT')<input name="name" value="{{ $category->name }}" required class="w-full border rounded px-3 py-2"><input name="icon_emoji" value="{{ $category->icon_emoji }}" maxlength="10" placeholder="Emoji" class="w-full border rounded px-3 py-2"><textarea name="description" rows="2" class="w-full border rounded px-3 py-2">{{ $category->description }}</textarea><input type="number" name="sort_order" value="{{ $category->sort_order }}" min="0" class="w-full border rounded px-3 py-2"><div class="flex gap-4"><label><input type="checkbox" name="is_active" value="1" @checked($category->is_active)> Active</label><label><input type="checkbox" name="is_popular" value="1" @checked($category->is_popular)> Popular</label></div><button class="bg-blue-600 text-white px-4 py-2 rounded">Save</button></form></div></details><form method="POST" action="{{ route('admin.partners.menu.categories.destroy', [$partner, $category]) }}" onsubmit="return confirm('Delete this category and its items?')">@csrf @method('DELETE')<button class="text-red-600 text-sm">Delete</button></form></div></div>
        <div class="divide-y">
        @forelse($category->items as $item)
            <details><summary class="list-none cursor-pointer px-6 py-4 hover:bg-gray-50 flex items-center gap-4"><div class="w-12 h-12 rounded bg-gray-100 overflow-hidden flex items-center justify-center">@if($item->image_url)<img src="{{ $item->image_url }}" class="w-full h-full object-cover">@else<i class="fas fa-utensils text-gray-400"></i>@endif</div><div class="flex-1"><p class="font-medium">{{ $item->name }}</p><p class="text-xs text-gray-500">{{ $item->unit ?: 'item' }} @if($item->requires_prescription) · Prescription required @endif</p></div><p class="font-semibold">₱{{ number_format($item->price, 2) }}</p><span class="px-2 py-1 rounded-full text-xs {{ $item->is_available ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600' }}">{{ $item->is_available ? 'Available' : 'Unavailable' }}</span><i class="fas fa-chevron-down text-gray-400"></i></summary>
                <div class="p-6 bg-gray-50 border-t"><form method="POST" action="{{ route('admin.partners.menu.items.update', [$partner, $item]) }}" class="space-y-3">@csrf @method('PUT')<div class="grid grid-cols-1 md:grid-cols-4 gap-3"><input name="name" value="{{ $item->name }}" required class="border rounded px-3 py-2"><select name="menu_category_id" class="border rounded px-3 py-2">@foreach($partner->menuCategories as $option)<option value="{{ $option->id }}" @selected($item->menu_category_id === $option->id)>{{ $option->name }}</option>@endforeach</select><input type="number" name="price" value="{{ $item->price }}" step="0.01" min="0" required class="border rounded px-3 py-2"><input type="number" name="original_price" value="{{ $item->original_price }}" step="0.01" min="0" placeholder="Original price" class="border rounded px-3 py-2"></div><div class="grid grid-cols-1 md:grid-cols-3 gap-3"><input name="unit" value="{{ $item->unit }}" placeholder="Unit" class="border rounded px-3 py-2"><input type="number" name="sort_order" value="{{ $item->sort_order }}" min="0" class="border rounded px-3 py-2"><input type="url" name="image_url" value="{{ $item->image_url }}" placeholder="Image URL" class="border rounded px-3 py-2"></div><textarea name="description" rows="2" class="w-full border rounded px-3 py-2">{{ $item->description }}</textarea><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><input name="tags" value="{{ implode(', ', $item->tags ?? []) }}" placeholder="Tags" class="border rounded px-3 py-2"><input name="options" value="{{ $item->options ? json_encode($item->options, JSON_UNESCAPED_SLASHES) : '' }}" placeholder="Options JSON" class="border rounded px-3 py-2"></div><div class="flex flex-wrap gap-5 text-sm"><label><input type="checkbox" name="is_available" value="1" @checked($item->is_available)> Available</label><label><input type="checkbox" name="is_popular" value="1" @checked($item->is_popular)> Popular</label><label><input type="checkbox" name="is_featured" value="1" @checked($item->is_featured)> Featured</label><label><input type="checkbox" name="is_best_seller" value="1" @checked($item->is_best_seller)> Best seller</label><label><input type="checkbox" name="requires_prescription" value="1" @checked($item->requires_prescription)> Prescription</label></div><div class="flex gap-3"><button class="bg-blue-600 text-white px-4 py-2 rounded">Save Item</button></div></form><form method="POST" action="{{ route('admin.partners.menu.items.destroy', [$partner, $item]) }}" class="mt-3" onsubmit="return confirm('Delete this menu item?')">@csrf @method('DELETE')<button class="text-red-600 text-sm">Delete item</button></form></div>
            </details>
        @empty<p class="px-6 py-8 text-center text-gray-400"><x-empty-state icon="fa-inbox" title="No items" description="No items in this category." /></p>@endforelse
        </div>
    </section>
@empty<div class="bg-white rounded-xl p-10 text-center text-gray-400"><x-empty-state icon="fa-inbox" title="No menu categories" description="No menu categories yet." /></div>@endforelse
</div>
@endsection
