@php($editing = isset($article))
<form method="POST" action="{{ $editing ? route('admin.faq.articles.update', $article) : route('admin.faq.articles.store') }}" class="max-w-4xl bg-white rounded-xl shadow-sm p-6 space-y-5">
    @csrf @if($editing) @method('PUT') @endif
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4"><div class="md:col-span-2"><label class="block text-sm font-medium mb-1">Title</label><input name="title" value="{{ old('title', $article->title ?? '') }}" required class="w-full border rounded-lg px-3 py-2"></div><div><label class="block text-sm font-medium mb-1">Category</label><select name="category_id" required class="w-full border rounded-lg px-3 py-2"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $article->category_id ?? '') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></div></div>
    <div><label class="block text-sm font-medium mb-1">Excerpt</label><textarea name="excerpt" rows="2" class="w-full border rounded-lg px-3 py-2">{{ old('excerpt', $article->excerpt ?? '') }}</textarea></div>
    <div><label class="block text-sm font-medium mb-1">Content</label><textarea name="content" rows="12" required class="w-full border rounded-lg px-3 py-2">{{ old('content', $article->content ?? '') }}</textarea></div>
    <div><label class="block text-sm font-medium mb-1">Tags <span class="font-normal text-gray-500">(comma-separated)</span></label><input name="tags" value="{{ old('tags', isset($article) ? implode(', ', $article->tags ?? []) : '') }}" class="w-full border rounded-lg px-3 py-2"></div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label class="block text-sm font-medium mb-1">Meta title</label><input name="meta_title" value="{{ old('meta_title', $article->meta_title ?? '') }}" class="w-full border rounded-lg px-3 py-2"></div><div><label class="block text-sm font-medium mb-1">Sort order</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $article->sort_order ?? 0) }}" class="w-full border rounded-lg px-3 py-2"></div></div>
    <div><label class="block text-sm font-medium mb-1">Meta description</label><textarea name="meta_description" rows="2" class="w-full border rounded-lg px-3 py-2">{{ old('meta_description', $article->meta_description ?? '') }}</textarea></div>
    <div class="flex gap-6"><label class="flex items-center gap-2"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $article->is_published ?? false))> Published</label><label class="flex items-center gap-2"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $article->is_featured ?? false))> Featured</label></div>
    <div class="flex gap-3"><button class="bg-blue-600 text-white px-5 py-2 rounded-lg">{{ $editing ? 'Save Changes' : 'Create Article' }}</button><a href="{{ route('admin.faq.articles') }}" class="border px-5 py-2 rounded-lg">Cancel</a></div>
</form>
